version: '3'

volumes:
    db_data:
        driver: local

services:

  postgres:
    container_name: postgres
    image: postgres:latest
#    volumes:
#      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

  backend:
    container_name: backend
    build: ./back/
    volumes:
      - ./back/src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
        - backend
    restart: always

#
#    front:
#      container_name: front
#      build: ./front/
#      volumes:
#          - "./frontend:/app"
#      ports:
#          - "80:80"
#      depends_on:
#        - back
#      networks:
#          - backend
#      restart: always


networks:
  backend: